// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package com.ylpu.kepler.scheduler.core.rpc.entity;

public final class WorkerGrpc {
  private WorkerGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkerRequestRpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WorkerRequestRpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkerParameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WorkerParameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkerResponseRpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WorkerResponseRpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JobStatusRequestRpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JobStatusRequestRpc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014worker.proto\032\037google/protobuf/timestam" +
      "p.proto\"\346\001\n\020WorkerRequestRpc\022\n\n\002id\030\001 \001(\005" +
      "\022\020\n\010nodeType\030\002 \001(\005\022\014\n\004host\030\003 \001(\t\022\014\n\004port" +
      "\030\004 \001(\005\022\021\n\tnodeGroup\030\005 \001(\t\022\023\n\013zkdirectory" +
      "\030\006 \001(\t\022\020\n\010cpuUsage\030\007 \001(\001\022\023\n\013memoryUsage\030" +
      "\010 \001(\001\0225\n\021lastHeartbeatTime\030\t \001(\0132\032.googl" +
      "e.protobuf.Timestamp\022\022\n\nnodeStatus\030\n \001(\005" +
      "\"#\n\017WorkerParameter\022\020\n\010hostname\030\001 \001(\t\"R\n" +
      "\021WorkerResponseRpc\022\n\n\002id\030\001 \001(\005\022\021\n\terrorC" +
      "ode\030\002 \001(\005\022\020\n\010errorMsg\030\003 \001(\t\022\014\n\004data\030\004 \001(",
      "\014\";\n\023JobStatusRequestRpc\022\021\n\trequestId\030\001 " +
      "\001(\t\022\021\n\ttaskState\030\003 \001(\0052\353\001\n\021GrpcWorkerSer" +
      "vice\022/\n\007incTask\022\020.WorkerParameter\032\022.Work" +
      "erResponseRpc\022/\n\007decTask\022\020.WorkerParamet" +
      "er\032\022.WorkerResponseRpc\0227\n\016updateResource" +
      "\022\021.WorkerRequestRpc\032\022.WorkerResponseRpc\022" +
      ";\n\017updateJobStatus\022\024.JobStatusRequestRpc" +
      "\032\022.WorkerResponseRpcB>\n.com.ylpu.ke" +
      "pler.scheduler.core.rpc.entityB\nWorkerGr" +
      "pcP\001P\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_WorkerRequestRpc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WorkerRequestRpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WorkerRequestRpc_descriptor,
        new java.lang.String[] { "Id", "NodeType", "Host", "Port", "NodeGroup", "Zkdirectory", "CpuUsage", "MemoryUsage", "LastHeartbeatTime", "NodeStatus", });
    internal_static_WorkerParameter_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WorkerParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WorkerParameter_descriptor,
        new java.lang.String[] { "Hostname", });
    internal_static_WorkerResponseRpc_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_WorkerResponseRpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WorkerResponseRpc_descriptor,
        new java.lang.String[] { "Id", "ErrorCode", "ErrorMsg", "Data", });
    internal_static_JobStatusRequestRpc_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_JobStatusRequestRpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JobStatusRequestRpc_descriptor,
        new java.lang.String[] { "RequestId", "TaskState", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
