// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job.proto

package com.ylpu.thales.scheduler.core.rpc.entity;

public final class JobGrpc {
    private JobGrpc() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor internal_static_JobRequestRpc_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_JobRequestRpc_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_JobInstanceRequestRpc_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_JobInstanceRequestRpc_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_JobInstanceResponseRpc_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_JobInstanceResponseRpc_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\tjob.proto\032\037google/protobuf/timestamp.p"
                        + "roto\"\257\003\n\rJobRequestRpc\022\n\n\002id\030\001 \001(\005\022\017\n\007jo"
                        + "bName\030\002 \001(\t\022\017\n\007jobType\030\003 \001(\005\022\023\n\013jobPrior"
                        + "ity\030\004 \001(\005\022\021\n\tcreatorId\030\005 \001(\t\022\020\n\010ownerIds"
                        + "\030\006 \001(\t\022\022\n\nalertUsers\030\007 \001(\t\022\022\n\nalertTypes"
                        + "\030\010 \001(\005\022\024\n\014scheduleCron\030\t \001(\t\022\027\n\017isSelfde"
                        + "pendent\030\n \001(\010\022\020\n\010jobCycle\030\013 \001(\005\022\025\n\rmaxRe"
                        + "trytimes\030\014 \001(\005\022\025\n\rretryInterval\030\r \001(\005\022\030\n"
                        + "\020executionTimeout\030\016 \001(\005\022\027\n\017workerGroupna"
                        + "me\030\017 \001(\t\022\027\n\017jobReleasestate\030\020 \001(\005\022\023\n\013des",
                "cription\030\021 \001(\t\022\030\n\020jobConfiguration\030\022 \001(\t"
                        + "\022$\n\014dependencies\030\023 \003(\0132\016.JobRequestRpc\"\234"
                        + "\003\n\025JobInstanceRequestRpc\022\n\n\002id\030\001 \001(\005\022\021\n\t"
                        + "requestId\030\002 \001(\t\022\033\n\003job\030\003 \001(\0132\016.JobReques"
                        + "tRpc\022\021\n\ttaskState\030\004 \001(\005\022\016\n\006logUrl\030\005 \001(\t\022"
                        + "\017\n\007logPath\030\006 \001(\t\022\016\n\006worker\030\007 \001(\t\022\023\n\013crea"
                        + "torName\030\010 \001(\t\022\024\n\014creatorEmail\030\t \001(\t\022\022\n\nr"
                        + "etryTimes\030\n \001(\005\022\013\n\003pid\030\013 \001(\005\022\025\n\rapplicat"
                        + "ionid\030\014 \001(\t\0220\n\014scheduleTime\030\r \001(\0132\032.goog"
                        + "le.protobuf.Timestamp\022-\n\tstartTime\030\016 \001(\013",
                "2\032.google.protobuf.Timestamp\022+\n\007endTime\030"
                        + "\017 \001(\0132\032.google.protobuf.Timestamp\022\022\n\nela"
                        + "pseTime\030\020 \001(\005\"~\n\026JobInstanceResponseRpc\022"
                        + "\n\n\002id\030\001 \001(\005\022\022\n\nresponseId\030\002 \001(\t\022\021\n\ttaskS"
                        + "tate\030\003 \001(\005\022\021\n\terrorCode\030\004 \001(\005\022\020\n\010errorMs"
                        + "g\030\005 \001(\t\022\014\n\004data\030\006 \001(\0142\204\001\n\016GrpcJobService"
                        + "\0229\n\006submit\022\026.JobInstanceRequestRpc\032\027.Job"
                        + "InstanceResponseRpc\0227\n\004kill\022\026.JobInstanc"
                        + "eRequestRpc\032\027.JobInstanceResponseRpcB;\n." + "com.ylpu.thales.scheduler.core.rpc.",
                "entityB\007JobGrpcP\001P\000b\006proto3" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {
                        com.google.protobuf.TimestampProto.getDescriptor(), },
                assigner);
        internal_static_JobRequestRpc_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_JobRequestRpc_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_JobRequestRpc_descriptor,
                new java.lang.String[] { "Id", "JobName", "JobType", "JobPriority", "CreatorId", "OwnerIds",
                        "AlertUsers", "AlertTypes", "ScheduleCron", "IsSelfdependent", "JobCycle", "MaxRetrytimes",
                        "RetryInterval", "ExecutionTimeout", "WorkerGroupname", "JobReleasestate", "Description",
                        "JobConfiguration", "Dependencies", });
        internal_static_JobInstanceRequestRpc_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_JobInstanceRequestRpc_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_JobInstanceRequestRpc_descriptor,
                new java.lang.String[] { "Id", "RequestId", "Job", "TaskState", "LogUrl", "LogPath", "Worker",
                        "CreatorName", "CreatorEmail", "RetryTimes", "Pid", "Applicationid", "ScheduleTime",
                        "StartTime", "EndTime", "ElapseTime", });
        internal_static_JobInstanceResponseRpc_descriptor = getDescriptor().getMessageTypes().get(2);
        internal_static_JobInstanceResponseRpc_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_JobInstanceResponseRpc_descriptor,
                new java.lang.String[] { "Id", "ResponseId", "TaskState", "ErrorCode", "ErrorMsg", "Data", });
        com.google.protobuf.TimestampProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
