// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job.proto

package com.ylpu.thales.scheduler.core.rpc.entity;

public interface JobInstanceResponseRpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JobInstanceResponseRpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string responseId = 2;</code>
   */
  java.lang.String getResponseId();
  /**
   * <code>string responseId = 2;</code>
   */
  com.google.protobuf.ByteString
      getResponseIdBytes();

  /**
   * <code>int32 taskState = 3;</code>
   */
  int getTaskState();

  /**
   * <code>int32 errorCode = 4;</code>
   */
  int getErrorCode();

  /**
   * <code>string errorMsg = 5;</code>
   */
  java.lang.String getErrorMsg();
  /**
   * <code>string errorMsg = 5;</code>
   */
  com.google.protobuf.ByteString
      getErrorMsgBytes();

  /**
   * <code>bytes data = 6;</code>
   */
  com.google.protobuf.ByteString getData();
}
