// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job.proto

package com.ylpu.thales.scheduler.core.rpc.entity;

public interface JobRequestRpcOrBuilder extends
        // @@protoc_insertion_point(interface_extends:JobRequestRpc)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string jobName = 2;</code>
     */
    java.lang.String getJobName();

    /**
     * <code>string jobName = 2;</code>
     */
    com.google.protobuf.ByteString getJobNameBytes();

    /**
     * <code>int32 jobType = 3;</code>
     */
    int getJobType();

    /**
     * <code>int32 jobPriority = 4;</code>
     */
    int getJobPriority();

    /**
     * <code>string creatorId = 5;</code>
     */
    java.lang.String getCreatorId();

    /**
     * <code>string creatorId = 5;</code>
     */
    com.google.protobuf.ByteString getCreatorIdBytes();

    /**
     * <code>string ownerIds = 6;</code>
     */
    java.lang.String getOwnerIds();

    /**
     * <code>string ownerIds = 6;</code>
     */
    com.google.protobuf.ByteString getOwnerIdsBytes();

    /**
     * <code>string alertUsers = 7;</code>
     */
    java.lang.String getAlertUsers();

    /**
     * <code>string alertUsers = 7;</code>
     */
    com.google.protobuf.ByteString getAlertUsersBytes();

    /**
     * <code>int32 alertTypes = 8;</code>
     */
    int getAlertTypes();

    /**
     * <code>string scheduleCron = 9;</code>
     */
    java.lang.String getScheduleCron();

    /**
     * <code>string scheduleCron = 9;</code>
     */
    com.google.protobuf.ByteString getScheduleCronBytes();

    /**
     * <code>bool isSelfdependent = 10;</code>
     */
    boolean getIsSelfdependent();

    /**
     * <code>int32 jobCycle = 11;</code>
     */
    int getJobCycle();

    /**
     * <code>int32 maxRetrytimes = 12;</code>
     */
    int getMaxRetrytimes();

    /**
     * <code>int32 retryInterval = 13;</code>
     */
    int getRetryInterval();

    /**
     * <code>int32 executionTimeout = 14;</code>
     */
    int getExecutionTimeout();

    /**
     * <code>string workerGroupname = 15;</code>
     */
    java.lang.String getWorkerGroupname();

    /**
     * <code>string workerGroupname = 15;</code>
     */
    com.google.protobuf.ByteString getWorkerGroupnameBytes();

    /**
     * <code>int32 jobReleasestate = 16;</code>
     */
    int getJobReleasestate();

    /**
     * <code>string description = 17;</code>
     */
    java.lang.String getDescription();

    /**
     * <code>string description = 17;</code>
     */
    com.google.protobuf.ByteString getDescriptionBytes();

    /**
     * <code>string jobConfiguration = 18;</code>
     */
    java.lang.String getJobConfiguration();

    /**
     * <code>string jobConfiguration = 18;</code>
     */
    com.google.protobuf.ByteString getJobConfigurationBytes();

    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    java.util.List<com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc> getDependenciesList();

    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc getDependencies(int index);

    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    int getDependenciesCount();

    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    java.util.List<? extends com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpcOrBuilder> getDependenciesOrBuilderList();

    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpcOrBuilder getDependenciesOrBuilder(int index);
}
