// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job.proto

package com.ylpu.thales.scheduler.core.rpc.entity;

/**
 * Protobuf type {@code JobRequestRpc}
 */
public  final class JobRequestRpc extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:JobRequestRpc)
    JobRequestRpcOrBuilder {
  // Use JobRequestRpc.newBuilder() to construct.
  private JobRequestRpc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JobRequestRpc() {
    id_ = 0;
    jobName_ = "";
    jobType_ = 0;
    jobPriority_ = 0;
    creatorId_ = "";
    ownerIds_ = "";
    alertUsers_ = "";
    alertTypes_ = 0;
    scheduleCron_ = "";
    isSelfdependent_ = false;
    jobCycle_ = 0;
    maxRetrytimes_ = 0;
    retryInterval_ = 0;
    executionTimeout_ = 0;
    workerGroupname_ = "";
    jobReleasestate_ = 0;
    description_ = "";
    jobConfiguration_ = "";
    dependencies_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private JobRequestRpc(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            jobName_ = s;
            break;
          }
          case 24: {

            jobType_ = input.readInt32();
            break;
          }
          case 32: {

            jobPriority_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            creatorId_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            ownerIds_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            alertUsers_ = s;
            break;
          }
          case 64: {

            alertTypes_ = input.readInt32();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            scheduleCron_ = s;
            break;
          }
          case 80: {

            isSelfdependent_ = input.readBool();
            break;
          }
          case 88: {

            jobCycle_ = input.readInt32();
            break;
          }
          case 96: {

            maxRetrytimes_ = input.readInt32();
            break;
          }
          case 104: {

            retryInterval_ = input.readInt32();
            break;
          }
          case 112: {

            executionTimeout_ = input.readInt32();
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            workerGroupname_ = s;
            break;
          }
          case 128: {

            jobReleasestate_ = input.readInt32();
            break;
          }
          case 138: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 146: {
            java.lang.String s = input.readStringRequireUtf8();

            jobConfiguration_ = s;
            break;
          }
          case 154: {
            if (!((mutable_bitField0_ & 0x00040000) == 0x00040000)) {
              dependencies_ = new java.util.ArrayList<com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc>();
              mutable_bitField0_ |= 0x00040000;
            }
            dependencies_.add(
                input.readMessage(com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00040000) == 0x00040000)) {
        dependencies_ = java.util.Collections.unmodifiableList(dependencies_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ylpu.thales.scheduler.core.rpc.entity.JobGrpc.internal_static_JobRequestRpc_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ylpu.thales.scheduler.core.rpc.entity.JobGrpc.internal_static_JobRequestRpc_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.class, com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int JOBNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object jobName_;
  /**
   * <code>string jobName = 2;</code>
   */
  public java.lang.String getJobName() {
    java.lang.Object ref = jobName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobName_ = s;
      return s;
    }
  }
  /**
   * <code>string jobName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getJobNameBytes() {
    java.lang.Object ref = jobName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOBTYPE_FIELD_NUMBER = 3;
  private int jobType_;
  /**
   * <code>int32 jobType = 3;</code>
   */
  public int getJobType() {
    return jobType_;
  }

  public static final int JOBPRIORITY_FIELD_NUMBER = 4;
  private int jobPriority_;
  /**
   * <code>int32 jobPriority = 4;</code>
   */
  public int getJobPriority() {
    return jobPriority_;
  }

  public static final int CREATORID_FIELD_NUMBER = 5;
  private volatile java.lang.Object creatorId_;
  /**
   * <code>string creatorId = 5;</code>
   */
  public java.lang.String getCreatorId() {
    java.lang.Object ref = creatorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      creatorId_ = s;
      return s;
    }
  }
  /**
   * <code>string creatorId = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCreatorIdBytes() {
    java.lang.Object ref = creatorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      creatorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OWNERIDS_FIELD_NUMBER = 6;
  private volatile java.lang.Object ownerIds_;
  /**
   * <code>string ownerIds = 6;</code>
   */
  public java.lang.String getOwnerIds() {
    java.lang.Object ref = ownerIds_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ownerIds_ = s;
      return s;
    }
  }
  /**
   * <code>string ownerIds = 6;</code>
   */
  public com.google.protobuf.ByteString
      getOwnerIdsBytes() {
    java.lang.Object ref = ownerIds_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ownerIds_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALERTUSERS_FIELD_NUMBER = 7;
  private volatile java.lang.Object alertUsers_;
  /**
   * <code>string alertUsers = 7;</code>
   */
  public java.lang.String getAlertUsers() {
    java.lang.Object ref = alertUsers_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alertUsers_ = s;
      return s;
    }
  }
  /**
   * <code>string alertUsers = 7;</code>
   */
  public com.google.protobuf.ByteString
      getAlertUsersBytes() {
    java.lang.Object ref = alertUsers_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alertUsers_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALERTTYPES_FIELD_NUMBER = 8;
  private int alertTypes_;
  /**
   * <code>int32 alertTypes = 8;</code>
   */
  public int getAlertTypes() {
    return alertTypes_;
  }

  public static final int SCHEDULECRON_FIELD_NUMBER = 9;
  private volatile java.lang.Object scheduleCron_;
  /**
   * <code>string scheduleCron = 9;</code>
   */
  public java.lang.String getScheduleCron() {
    java.lang.Object ref = scheduleCron_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scheduleCron_ = s;
      return s;
    }
  }
  /**
   * <code>string scheduleCron = 9;</code>
   */
  public com.google.protobuf.ByteString
      getScheduleCronBytes() {
    java.lang.Object ref = scheduleCron_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scheduleCron_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISSELFDEPENDENT_FIELD_NUMBER = 10;
  private boolean isSelfdependent_;
  /**
   * <code>bool isSelfdependent = 10;</code>
   */
  public boolean getIsSelfdependent() {
    return isSelfdependent_;
  }

  public static final int JOBCYCLE_FIELD_NUMBER = 11;
  private int jobCycle_;
  /**
   * <code>int32 jobCycle = 11;</code>
   */
  public int getJobCycle() {
    return jobCycle_;
  }

  public static final int MAXRETRYTIMES_FIELD_NUMBER = 12;
  private int maxRetrytimes_;
  /**
   * <code>int32 maxRetrytimes = 12;</code>
   */
  public int getMaxRetrytimes() {
    return maxRetrytimes_;
  }

  public static final int RETRYINTERVAL_FIELD_NUMBER = 13;
  private int retryInterval_;
  /**
   * <code>int32 retryInterval = 13;</code>
   */
  public int getRetryInterval() {
    return retryInterval_;
  }

  public static final int EXECUTIONTIMEOUT_FIELD_NUMBER = 14;
  private int executionTimeout_;
  /**
   * <code>int32 executionTimeout = 14;</code>
   */
  public int getExecutionTimeout() {
    return executionTimeout_;
  }

  public static final int WORKERGROUPNAME_FIELD_NUMBER = 15;
  private volatile java.lang.Object workerGroupname_;
  /**
   * <code>string workerGroupname = 15;</code>
   */
  public java.lang.String getWorkerGroupname() {
    java.lang.Object ref = workerGroupname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      workerGroupname_ = s;
      return s;
    }
  }
  /**
   * <code>string workerGroupname = 15;</code>
   */
  public com.google.protobuf.ByteString
      getWorkerGroupnameBytes() {
    java.lang.Object ref = workerGroupname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      workerGroupname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOBRELEASESTATE_FIELD_NUMBER = 16;
  private int jobReleasestate_;
  /**
   * <code>int32 jobReleasestate = 16;</code>
   */
  public int getJobReleasestate() {
    return jobReleasestate_;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 17;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 17;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 17;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOBCONFIGURATION_FIELD_NUMBER = 18;
  private volatile java.lang.Object jobConfiguration_;
  /**
   * <code>string jobConfiguration = 18;</code>
   */
  public java.lang.String getJobConfiguration() {
    java.lang.Object ref = jobConfiguration_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobConfiguration_ = s;
      return s;
    }
  }
  /**
   * <code>string jobConfiguration = 18;</code>
   */
  public com.google.protobuf.ByteString
      getJobConfigurationBytes() {
    java.lang.Object ref = jobConfiguration_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobConfiguration_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPENDENCIES_FIELD_NUMBER = 19;
  private java.util.List<com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc> dependencies_;
  /**
   * <code>repeated .JobRequestRpc dependencies = 19;</code>
   */
  public java.util.List<com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc> getDependenciesList() {
    return dependencies_;
  }
  /**
   * <code>repeated .JobRequestRpc dependencies = 19;</code>
   */
  public java.util.List<? extends com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpcOrBuilder> 
      getDependenciesOrBuilderList() {
    return dependencies_;
  }
  /**
   * <code>repeated .JobRequestRpc dependencies = 19;</code>
   */
  public int getDependenciesCount() {
    return dependencies_.size();
  }
  /**
   * <code>repeated .JobRequestRpc dependencies = 19;</code>
   */
  public com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc getDependencies(int index) {
    return dependencies_.get(index);
  }
  /**
   * <code>repeated .JobRequestRpc dependencies = 19;</code>
   */
  public com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpcOrBuilder getDependenciesOrBuilder(
      int index) {
    return dependencies_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getJobNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, jobName_);
    }
    if (jobType_ != 0) {
      output.writeInt32(3, jobType_);
    }
    if (jobPriority_ != 0) {
      output.writeInt32(4, jobPriority_);
    }
    if (!getCreatorIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, creatorId_);
    }
    if (!getOwnerIdsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, ownerIds_);
    }
    if (!getAlertUsersBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, alertUsers_);
    }
    if (alertTypes_ != 0) {
      output.writeInt32(8, alertTypes_);
    }
    if (!getScheduleCronBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, scheduleCron_);
    }
    if (isSelfdependent_ != false) {
      output.writeBool(10, isSelfdependent_);
    }
    if (jobCycle_ != 0) {
      output.writeInt32(11, jobCycle_);
    }
    if (maxRetrytimes_ != 0) {
      output.writeInt32(12, maxRetrytimes_);
    }
    if (retryInterval_ != 0) {
      output.writeInt32(13, retryInterval_);
    }
    if (executionTimeout_ != 0) {
      output.writeInt32(14, executionTimeout_);
    }
    if (!getWorkerGroupnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, workerGroupname_);
    }
    if (jobReleasestate_ != 0) {
      output.writeInt32(16, jobReleasestate_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 17, description_);
    }
    if (!getJobConfigurationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 18, jobConfiguration_);
    }
    for (int i = 0; i < dependencies_.size(); i++) {
      output.writeMessage(19, dependencies_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getJobNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, jobName_);
    }
    if (jobType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, jobType_);
    }
    if (jobPriority_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, jobPriority_);
    }
    if (!getCreatorIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, creatorId_);
    }
    if (!getOwnerIdsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, ownerIds_);
    }
    if (!getAlertUsersBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, alertUsers_);
    }
    if (alertTypes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, alertTypes_);
    }
    if (!getScheduleCronBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, scheduleCron_);
    }
    if (isSelfdependent_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, isSelfdependent_);
    }
    if (jobCycle_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, jobCycle_);
    }
    if (maxRetrytimes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, maxRetrytimes_);
    }
    if (retryInterval_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, retryInterval_);
    }
    if (executionTimeout_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, executionTimeout_);
    }
    if (!getWorkerGroupnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, workerGroupname_);
    }
    if (jobReleasestate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, jobReleasestate_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, description_);
    }
    if (!getJobConfigurationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, jobConfiguration_);
    }
    for (int i = 0; i < dependencies_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(19, dependencies_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc)) {
      return super.equals(obj);
    }
    com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc other = (com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getJobName()
        .equals(other.getJobName());
    result = result && (getJobType()
        == other.getJobType());
    result = result && (getJobPriority()
        == other.getJobPriority());
    result = result && getCreatorId()
        .equals(other.getCreatorId());
    result = result && getOwnerIds()
        .equals(other.getOwnerIds());
    result = result && getAlertUsers()
        .equals(other.getAlertUsers());
    result = result && (getAlertTypes()
        == other.getAlertTypes());
    result = result && getScheduleCron()
        .equals(other.getScheduleCron());
    result = result && (getIsSelfdependent()
        == other.getIsSelfdependent());
    result = result && (getJobCycle()
        == other.getJobCycle());
    result = result && (getMaxRetrytimes()
        == other.getMaxRetrytimes());
    result = result && (getRetryInterval()
        == other.getRetryInterval());
    result = result && (getExecutionTimeout()
        == other.getExecutionTimeout());
    result = result && getWorkerGroupname()
        .equals(other.getWorkerGroupname());
    result = result && (getJobReleasestate()
        == other.getJobReleasestate());
    result = result && getDescription()
        .equals(other.getDescription());
    result = result && getJobConfiguration()
        .equals(other.getJobConfiguration());
    result = result && getDependenciesList()
        .equals(other.getDependenciesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + JOBNAME_FIELD_NUMBER;
    hash = (53 * hash) + getJobName().hashCode();
    hash = (37 * hash) + JOBTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getJobType();
    hash = (37 * hash) + JOBPRIORITY_FIELD_NUMBER;
    hash = (53 * hash) + getJobPriority();
    hash = (37 * hash) + CREATORID_FIELD_NUMBER;
    hash = (53 * hash) + getCreatorId().hashCode();
    hash = (37 * hash) + OWNERIDS_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerIds().hashCode();
    hash = (37 * hash) + ALERTUSERS_FIELD_NUMBER;
    hash = (53 * hash) + getAlertUsers().hashCode();
    hash = (37 * hash) + ALERTTYPES_FIELD_NUMBER;
    hash = (53 * hash) + getAlertTypes();
    hash = (37 * hash) + SCHEDULECRON_FIELD_NUMBER;
    hash = (53 * hash) + getScheduleCron().hashCode();
    hash = (37 * hash) + ISSELFDEPENDENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSelfdependent());
    hash = (37 * hash) + JOBCYCLE_FIELD_NUMBER;
    hash = (53 * hash) + getJobCycle();
    hash = (37 * hash) + MAXRETRYTIMES_FIELD_NUMBER;
    hash = (53 * hash) + getMaxRetrytimes();
    hash = (37 * hash) + RETRYINTERVAL_FIELD_NUMBER;
    hash = (53 * hash) + getRetryInterval();
    hash = (37 * hash) + EXECUTIONTIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + getExecutionTimeout();
    hash = (37 * hash) + WORKERGROUPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getWorkerGroupname().hashCode();
    hash = (37 * hash) + JOBRELEASESTATE_FIELD_NUMBER;
    hash = (53 * hash) + getJobReleasestate();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + JOBCONFIGURATION_FIELD_NUMBER;
    hash = (53 * hash) + getJobConfiguration().hashCode();
    if (getDependenciesCount() > 0) {
      hash = (37 * hash) + DEPENDENCIES_FIELD_NUMBER;
      hash = (53 * hash) + getDependenciesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code JobRequestRpc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:JobRequestRpc)
      com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpcOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ylpu.thales.scheduler.core.rpc.entity.JobGrpc.internal_static_JobRequestRpc_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ylpu.thales.scheduler.core.rpc.entity.JobGrpc.internal_static_JobRequestRpc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.class, com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.Builder.class);
    }

    // Construct using com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDependenciesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      jobName_ = "";

      jobType_ = 0;

      jobPriority_ = 0;

      creatorId_ = "";

      ownerIds_ = "";

      alertUsers_ = "";

      alertTypes_ = 0;

      scheduleCron_ = "";

      isSelfdependent_ = false;

      jobCycle_ = 0;

      maxRetrytimes_ = 0;

      retryInterval_ = 0;

      executionTimeout_ = 0;

      workerGroupname_ = "";

      jobReleasestate_ = 0;

      description_ = "";

      jobConfiguration_ = "";

      if (dependenciesBuilder_ == null) {
        dependencies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00040000);
      } else {
        dependenciesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ylpu.thales.scheduler.core.rpc.entity.JobGrpc.internal_static_JobRequestRpc_descriptor;
    }

    public com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc getDefaultInstanceForType() {
      return com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.getDefaultInstance();
    }

    public com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc build() {
      com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc buildPartial() {
      com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc result = new com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.jobName_ = jobName_;
      result.jobType_ = jobType_;
      result.jobPriority_ = jobPriority_;
      result.creatorId_ = creatorId_;
      result.ownerIds_ = ownerIds_;
      result.alertUsers_ = alertUsers_;
      result.alertTypes_ = alertTypes_;
      result.scheduleCron_ = scheduleCron_;
      result.isSelfdependent_ = isSelfdependent_;
      result.jobCycle_ = jobCycle_;
      result.maxRetrytimes_ = maxRetrytimes_;
      result.retryInterval_ = retryInterval_;
      result.executionTimeout_ = executionTimeout_;
      result.workerGroupname_ = workerGroupname_;
      result.jobReleasestate_ = jobReleasestate_;
      result.description_ = description_;
      result.jobConfiguration_ = jobConfiguration_;
      if (dependenciesBuilder_ == null) {
        if (((bitField0_ & 0x00040000) == 0x00040000)) {
          dependencies_ = java.util.Collections.unmodifiableList(dependencies_);
          bitField0_ = (bitField0_ & ~0x00040000);
        }
        result.dependencies_ = dependencies_;
      } else {
        result.dependencies_ = dependenciesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc) {
        return mergeFrom((com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc other) {
      if (other == com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getJobName().isEmpty()) {
        jobName_ = other.jobName_;
        onChanged();
      }
      if (other.getJobType() != 0) {
        setJobType(other.getJobType());
      }
      if (other.getJobPriority() != 0) {
        setJobPriority(other.getJobPriority());
      }
      if (!other.getCreatorId().isEmpty()) {
        creatorId_ = other.creatorId_;
        onChanged();
      }
      if (!other.getOwnerIds().isEmpty()) {
        ownerIds_ = other.ownerIds_;
        onChanged();
      }
      if (!other.getAlertUsers().isEmpty()) {
        alertUsers_ = other.alertUsers_;
        onChanged();
      }
      if (other.getAlertTypes() != 0) {
        setAlertTypes(other.getAlertTypes());
      }
      if (!other.getScheduleCron().isEmpty()) {
        scheduleCron_ = other.scheduleCron_;
        onChanged();
      }
      if (other.getIsSelfdependent() != false) {
        setIsSelfdependent(other.getIsSelfdependent());
      }
      if (other.getJobCycle() != 0) {
        setJobCycle(other.getJobCycle());
      }
      if (other.getMaxRetrytimes() != 0) {
        setMaxRetrytimes(other.getMaxRetrytimes());
      }
      if (other.getRetryInterval() != 0) {
        setRetryInterval(other.getRetryInterval());
      }
      if (other.getExecutionTimeout() != 0) {
        setExecutionTimeout(other.getExecutionTimeout());
      }
      if (!other.getWorkerGroupname().isEmpty()) {
        workerGroupname_ = other.workerGroupname_;
        onChanged();
      }
      if (other.getJobReleasestate() != 0) {
        setJobReleasestate(other.getJobReleasestate());
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getJobConfiguration().isEmpty()) {
        jobConfiguration_ = other.jobConfiguration_;
        onChanged();
      }
      if (dependenciesBuilder_ == null) {
        if (!other.dependencies_.isEmpty()) {
          if (dependencies_.isEmpty()) {
            dependencies_ = other.dependencies_;
            bitField0_ = (bitField0_ & ~0x00040000);
          } else {
            ensureDependenciesIsMutable();
            dependencies_.addAll(other.dependencies_);
          }
          onChanged();
        }
      } else {
        if (!other.dependencies_.isEmpty()) {
          if (dependenciesBuilder_.isEmpty()) {
            dependenciesBuilder_.dispose();
            dependenciesBuilder_ = null;
            dependencies_ = other.dependencies_;
            bitField0_ = (bitField0_ & ~0x00040000);
            dependenciesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDependenciesFieldBuilder() : null;
          } else {
            dependenciesBuilder_.addAllMessages(other.dependencies_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object jobName_ = "";
    /**
     * <code>string jobName = 2;</code>
     */
    public java.lang.String getJobName() {
      java.lang.Object ref = jobName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string jobName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getJobNameBytes() {
      java.lang.Object ref = jobName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string jobName = 2;</code>
     */
    public Builder setJobName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jobName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string jobName = 2;</code>
     */
    public Builder clearJobName() {
      
      jobName_ = getDefaultInstance().getJobName();
      onChanged();
      return this;
    }
    /**
     * <code>string jobName = 2;</code>
     */
    public Builder setJobNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jobName_ = value;
      onChanged();
      return this;
    }

    private int jobType_ ;
    /**
     * <code>int32 jobType = 3;</code>
     */
    public int getJobType() {
      return jobType_;
    }
    /**
     * <code>int32 jobType = 3;</code>
     */
    public Builder setJobType(int value) {
      
      jobType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 jobType = 3;</code>
     */
    public Builder clearJobType() {
      
      jobType_ = 0;
      onChanged();
      return this;
    }

    private int jobPriority_ ;
    /**
     * <code>int32 jobPriority = 4;</code>
     */
    public int getJobPriority() {
      return jobPriority_;
    }
    /**
     * <code>int32 jobPriority = 4;</code>
     */
    public Builder setJobPriority(int value) {
      
      jobPriority_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 jobPriority = 4;</code>
     */
    public Builder clearJobPriority() {
      
      jobPriority_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object creatorId_ = "";
    /**
     * <code>string creatorId = 5;</code>
     */
    public java.lang.String getCreatorId() {
      java.lang.Object ref = creatorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creatorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string creatorId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCreatorIdBytes() {
      java.lang.Object ref = creatorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creatorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string creatorId = 5;</code>
     */
    public Builder setCreatorId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      creatorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string creatorId = 5;</code>
     */
    public Builder clearCreatorId() {
      
      creatorId_ = getDefaultInstance().getCreatorId();
      onChanged();
      return this;
    }
    /**
     * <code>string creatorId = 5;</code>
     */
    public Builder setCreatorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      creatorId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ownerIds_ = "";
    /**
     * <code>string ownerIds = 6;</code>
     */
    public java.lang.String getOwnerIds() {
      java.lang.Object ref = ownerIds_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownerIds_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ownerIds = 6;</code>
     */
    public com.google.protobuf.ByteString
        getOwnerIdsBytes() {
      java.lang.Object ref = ownerIds_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerIds_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ownerIds = 6;</code>
     */
    public Builder setOwnerIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ownerIds_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ownerIds = 6;</code>
     */
    public Builder clearOwnerIds() {
      
      ownerIds_ = getDefaultInstance().getOwnerIds();
      onChanged();
      return this;
    }
    /**
     * <code>string ownerIds = 6;</code>
     */
    public Builder setOwnerIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ownerIds_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object alertUsers_ = "";
    /**
     * <code>string alertUsers = 7;</code>
     */
    public java.lang.String getAlertUsers() {
      java.lang.Object ref = alertUsers_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alertUsers_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alertUsers = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAlertUsersBytes() {
      java.lang.Object ref = alertUsers_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alertUsers_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alertUsers = 7;</code>
     */
    public Builder setAlertUsers(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      alertUsers_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string alertUsers = 7;</code>
     */
    public Builder clearAlertUsers() {
      
      alertUsers_ = getDefaultInstance().getAlertUsers();
      onChanged();
      return this;
    }
    /**
     * <code>string alertUsers = 7;</code>
     */
    public Builder setAlertUsersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      alertUsers_ = value;
      onChanged();
      return this;
    }

    private int alertTypes_ ;
    /**
     * <code>int32 alertTypes = 8;</code>
     */
    public int getAlertTypes() {
      return alertTypes_;
    }
    /**
     * <code>int32 alertTypes = 8;</code>
     */
    public Builder setAlertTypes(int value) {
      
      alertTypes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 alertTypes = 8;</code>
     */
    public Builder clearAlertTypes() {
      
      alertTypes_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object scheduleCron_ = "";
    /**
     * <code>string scheduleCron = 9;</code>
     */
    public java.lang.String getScheduleCron() {
      java.lang.Object ref = scheduleCron_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scheduleCron_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string scheduleCron = 9;</code>
     */
    public com.google.protobuf.ByteString
        getScheduleCronBytes() {
      java.lang.Object ref = scheduleCron_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scheduleCron_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string scheduleCron = 9;</code>
     */
    public Builder setScheduleCron(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      scheduleCron_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string scheduleCron = 9;</code>
     */
    public Builder clearScheduleCron() {
      
      scheduleCron_ = getDefaultInstance().getScheduleCron();
      onChanged();
      return this;
    }
    /**
     * <code>string scheduleCron = 9;</code>
     */
    public Builder setScheduleCronBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      scheduleCron_ = value;
      onChanged();
      return this;
    }

    private boolean isSelfdependent_ ;
    /**
     * <code>bool isSelfdependent = 10;</code>
     */
    public boolean getIsSelfdependent() {
      return isSelfdependent_;
    }
    /**
     * <code>bool isSelfdependent = 10;</code>
     */
    public Builder setIsSelfdependent(boolean value) {
      
      isSelfdependent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isSelfdependent = 10;</code>
     */
    public Builder clearIsSelfdependent() {
      
      isSelfdependent_ = false;
      onChanged();
      return this;
    }

    private int jobCycle_ ;
    /**
     * <code>int32 jobCycle = 11;</code>
     */
    public int getJobCycle() {
      return jobCycle_;
    }
    /**
     * <code>int32 jobCycle = 11;</code>
     */
    public Builder setJobCycle(int value) {
      
      jobCycle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 jobCycle = 11;</code>
     */
    public Builder clearJobCycle() {
      
      jobCycle_ = 0;
      onChanged();
      return this;
    }

    private int maxRetrytimes_ ;
    /**
     * <code>int32 maxRetrytimes = 12;</code>
     */
    public int getMaxRetrytimes() {
      return maxRetrytimes_;
    }
    /**
     * <code>int32 maxRetrytimes = 12;</code>
     */
    public Builder setMaxRetrytimes(int value) {
      
      maxRetrytimes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 maxRetrytimes = 12;</code>
     */
    public Builder clearMaxRetrytimes() {
      
      maxRetrytimes_ = 0;
      onChanged();
      return this;
    }

    private int retryInterval_ ;
    /**
     * <code>int32 retryInterval = 13;</code>
     */
    public int getRetryInterval() {
      return retryInterval_;
    }
    /**
     * <code>int32 retryInterval = 13;</code>
     */
    public Builder setRetryInterval(int value) {
      
      retryInterval_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 retryInterval = 13;</code>
     */
    public Builder clearRetryInterval() {
      
      retryInterval_ = 0;
      onChanged();
      return this;
    }

    private int executionTimeout_ ;
    /**
     * <code>int32 executionTimeout = 14;</code>
     */
    public int getExecutionTimeout() {
      return executionTimeout_;
    }
    /**
     * <code>int32 executionTimeout = 14;</code>
     */
    public Builder setExecutionTimeout(int value) {
      
      executionTimeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 executionTimeout = 14;</code>
     */
    public Builder clearExecutionTimeout() {
      
      executionTimeout_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object workerGroupname_ = "";
    /**
     * <code>string workerGroupname = 15;</code>
     */
    public java.lang.String getWorkerGroupname() {
      java.lang.Object ref = workerGroupname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workerGroupname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string workerGroupname = 15;</code>
     */
    public com.google.protobuf.ByteString
        getWorkerGroupnameBytes() {
      java.lang.Object ref = workerGroupname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workerGroupname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string workerGroupname = 15;</code>
     */
    public Builder setWorkerGroupname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      workerGroupname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string workerGroupname = 15;</code>
     */
    public Builder clearWorkerGroupname() {
      
      workerGroupname_ = getDefaultInstance().getWorkerGroupname();
      onChanged();
      return this;
    }
    /**
     * <code>string workerGroupname = 15;</code>
     */
    public Builder setWorkerGroupnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      workerGroupname_ = value;
      onChanged();
      return this;
    }

    private int jobReleasestate_ ;
    /**
     * <code>int32 jobReleasestate = 16;</code>
     */
    public int getJobReleasestate() {
      return jobReleasestate_;
    }
    /**
     * <code>int32 jobReleasestate = 16;</code>
     */
    public Builder setJobReleasestate(int value) {
      
      jobReleasestate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 jobReleasestate = 16;</code>
     */
    public Builder clearJobReleasestate() {
      
      jobReleasestate_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 17;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 17;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 17;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 17;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 17;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object jobConfiguration_ = "";
    /**
     * <code>string jobConfiguration = 18;</code>
     */
    public java.lang.String getJobConfiguration() {
      java.lang.Object ref = jobConfiguration_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobConfiguration_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string jobConfiguration = 18;</code>
     */
    public com.google.protobuf.ByteString
        getJobConfigurationBytes() {
      java.lang.Object ref = jobConfiguration_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobConfiguration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string jobConfiguration = 18;</code>
     */
    public Builder setJobConfiguration(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jobConfiguration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string jobConfiguration = 18;</code>
     */
    public Builder clearJobConfiguration() {
      
      jobConfiguration_ = getDefaultInstance().getJobConfiguration();
      onChanged();
      return this;
    }
    /**
     * <code>string jobConfiguration = 18;</code>
     */
    public Builder setJobConfigurationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jobConfiguration_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc> dependencies_ =
      java.util.Collections.emptyList();
    private void ensureDependenciesIsMutable() {
      if (!((bitField0_ & 0x00040000) == 0x00040000)) {
        dependencies_ = new java.util.ArrayList<com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc>(dependencies_);
        bitField0_ |= 0x00040000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc, com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.Builder, com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpcOrBuilder> dependenciesBuilder_;

    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public java.util.List<com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc> getDependenciesList() {
      if (dependenciesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dependencies_);
      } else {
        return dependenciesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public int getDependenciesCount() {
      if (dependenciesBuilder_ == null) {
        return dependencies_.size();
      } else {
        return dependenciesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc getDependencies(int index) {
      if (dependenciesBuilder_ == null) {
        return dependencies_.get(index);
      } else {
        return dependenciesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public Builder setDependencies(
        int index, com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc value) {
      if (dependenciesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDependenciesIsMutable();
        dependencies_.set(index, value);
        onChanged();
      } else {
        dependenciesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public Builder setDependencies(
        int index, com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.Builder builderForValue) {
      if (dependenciesBuilder_ == null) {
        ensureDependenciesIsMutable();
        dependencies_.set(index, builderForValue.build());
        onChanged();
      } else {
        dependenciesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public Builder addDependencies(com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc value) {
      if (dependenciesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDependenciesIsMutable();
        dependencies_.add(value);
        onChanged();
      } else {
        dependenciesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public Builder addDependencies(
        int index, com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc value) {
      if (dependenciesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDependenciesIsMutable();
        dependencies_.add(index, value);
        onChanged();
      } else {
        dependenciesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public Builder addDependencies(
        com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.Builder builderForValue) {
      if (dependenciesBuilder_ == null) {
        ensureDependenciesIsMutable();
        dependencies_.add(builderForValue.build());
        onChanged();
      } else {
        dependenciesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public Builder addDependencies(
        int index, com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.Builder builderForValue) {
      if (dependenciesBuilder_ == null) {
        ensureDependenciesIsMutable();
        dependencies_.add(index, builderForValue.build());
        onChanged();
      } else {
        dependenciesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public Builder addAllDependencies(
        java.lang.Iterable<? extends com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc> values) {
      if (dependenciesBuilder_ == null) {
        ensureDependenciesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dependencies_);
        onChanged();
      } else {
        dependenciesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public Builder clearDependencies() {
      if (dependenciesBuilder_ == null) {
        dependencies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00040000);
        onChanged();
      } else {
        dependenciesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public Builder removeDependencies(int index) {
      if (dependenciesBuilder_ == null) {
        ensureDependenciesIsMutable();
        dependencies_.remove(index);
        onChanged();
      } else {
        dependenciesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.Builder getDependenciesBuilder(
        int index) {
      return getDependenciesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpcOrBuilder getDependenciesOrBuilder(
        int index) {
      if (dependenciesBuilder_ == null) {
        return dependencies_.get(index);  } else {
        return dependenciesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public java.util.List<? extends com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpcOrBuilder> 
         getDependenciesOrBuilderList() {
      if (dependenciesBuilder_ != null) {
        return dependenciesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dependencies_);
      }
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.Builder addDependenciesBuilder() {
      return getDependenciesFieldBuilder().addBuilder(
          com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.getDefaultInstance());
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.Builder addDependenciesBuilder(
        int index) {
      return getDependenciesFieldBuilder().addBuilder(
          index, com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.getDefaultInstance());
    }
    /**
     * <code>repeated .JobRequestRpc dependencies = 19;</code>
     */
    public java.util.List<com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.Builder> 
         getDependenciesBuilderList() {
      return getDependenciesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc, com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.Builder, com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpcOrBuilder> 
        getDependenciesFieldBuilder() {
      if (dependenciesBuilder_ == null) {
        dependenciesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc, com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc.Builder, com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpcOrBuilder>(
                dependencies_,
                ((bitField0_ & 0x00040000) == 0x00040000),
                getParentForChildren(),
                isClean());
        dependencies_ = null;
      }
      return dependenciesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:JobRequestRpc)
  }

  // @@protoc_insertion_point(class_scope:JobRequestRpc)
  private static final com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc();
  }

  public static com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobRequestRpc>
      PARSER = new com.google.protobuf.AbstractParser<JobRequestRpc>() {
    public JobRequestRpc parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new JobRequestRpc(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JobRequestRpc> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JobRequestRpc> getParserForType() {
    return PARSER;
  }

  public com.ylpu.thales.scheduler.core.rpc.entity.JobRequestRpc getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

