// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package com.ylpu.thales.scheduler.core.rpc.entity;

/**
 * Protobuf type {@code WorkerRequestRpc}
 */
public final class WorkerRequestRpc extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:WorkerRequestRpc)
        WorkerRequestRpcOrBuilder {
    // Use WorkerRequestRpc.newBuilder() to construct.
    private WorkerRequestRpc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private WorkerRequestRpc() {
        id_ = 0;
        workerType_ = 0;
        host_ = "";
        port_ = 0;
        workerGroup_ = "";
        zkdirectory_ = "";
        cpuUsage_ = 0D;
        memoryUsage_ = 0D;
        workerStatus_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private WorkerRequestRpc(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                case 0:
                    done = true;
                    break;
                default: {
                    if (!input.skipField(tag)) {
                        done = true;
                    }
                    break;
                }
                case 8: {

                    id_ = input.readInt32();
                    break;
                }
                case 16: {

                    workerType_ = input.readInt32();
                    break;
                }
                case 26: {
                    java.lang.String s = input.readStringRequireUtf8();

                    host_ = s;
                    break;
                }
                case 32: {

                    port_ = input.readInt32();
                    break;
                }
                case 42: {
                    java.lang.String s = input.readStringRequireUtf8();

                    workerGroup_ = s;
                    break;
                }
                case 50: {
                    java.lang.String s = input.readStringRequireUtf8();

                    zkdirectory_ = s;
                    break;
                }
                case 57: {

                    cpuUsage_ = input.readDouble();
                    break;
                }
                case 65: {

                    memoryUsage_ = input.readDouble();
                    break;
                }
                case 74: {
                    com.google.protobuf.Timestamp.Builder subBuilder = null;
                    if (lastHeartbeatTime_ != null) {
                        subBuilder = lastHeartbeatTime_.toBuilder();
                    }
                    lastHeartbeatTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
                    if (subBuilder != null) {
                        subBuilder.mergeFrom(lastHeartbeatTime_);
                        lastHeartbeatTime_ = subBuilder.buildPartial();
                    }

                    break;
                }
                case 80: {

                    workerStatus_ = input.readInt32();
                    break;
                }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
        } finally {
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.ylpu.thales.scheduler.core.rpc.entity.WorkerGrpc.internal_static_WorkerRequestRpc_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.ylpu.thales.scheduler.core.rpc.entity.WorkerGrpc.internal_static_WorkerRequestRpc_fieldAccessorTable
                .ensureFieldAccessorsInitialized(com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc.class,
                        com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;

    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
        return id_;
    }

    public static final int WORKERTYPE_FIELD_NUMBER = 2;
    private int workerType_;

    /**
     * <code>int32 workerType = 2;</code>
     */
    public int getWorkerType() {
        return workerType_;
    }

    public static final int HOST_FIELD_NUMBER = 3;
    private volatile java.lang.Object host_;

    /**
     * <code>string host = 3;</code>
     */
    public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            host_ = s;
            return s;
        }
    }

    /**
     * <code>string host = 3;</code>
     */
    public com.google.protobuf.ByteString getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            host_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;

    /**
     * <code>int32 port = 4;</code>
     */
    public int getPort() {
        return port_;
    }

    public static final int WORKERGROUP_FIELD_NUMBER = 5;
    private volatile java.lang.Object workerGroup_;

    /**
     * <code>string workerGroup = 5;</code>
     */
    public java.lang.String getWorkerGroup() {
        java.lang.Object ref = workerGroup_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            workerGroup_ = s;
            return s;
        }
    }

    /**
     * <code>string workerGroup = 5;</code>
     */
    public com.google.protobuf.ByteString getWorkerGroupBytes() {
        java.lang.Object ref = workerGroup_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            workerGroup_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ZKDIRECTORY_FIELD_NUMBER = 6;
    private volatile java.lang.Object zkdirectory_;

    /**
     * <code>string zkdirectory = 6;</code>
     */
    public java.lang.String getZkdirectory() {
        java.lang.Object ref = zkdirectory_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            zkdirectory_ = s;
            return s;
        }
    }

    /**
     * <code>string zkdirectory = 6;</code>
     */
    public com.google.protobuf.ByteString getZkdirectoryBytes() {
        java.lang.Object ref = zkdirectory_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            zkdirectory_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int CPUUSAGE_FIELD_NUMBER = 7;
    private double cpuUsage_;

    /**
     * <code>double cpuUsage = 7;</code>
     */
    public double getCpuUsage() {
        return cpuUsage_;
    }

    public static final int MEMORYUSAGE_FIELD_NUMBER = 8;
    private double memoryUsage_;

    /**
     * <code>double memoryUsage = 8;</code>
     */
    public double getMemoryUsage() {
        return memoryUsage_;
    }

    public static final int LASTHEARTBEATTIME_FIELD_NUMBER = 9;
    private com.google.protobuf.Timestamp lastHeartbeatTime_;

    /**
     * <code>.google.protobuf.Timestamp lastHeartbeatTime = 9;</code>
     */
    public boolean hasLastHeartbeatTime() {
        return lastHeartbeatTime_ != null;
    }

    /**
     * <code>.google.protobuf.Timestamp lastHeartbeatTime = 9;</code>
     */
    public com.google.protobuf.Timestamp getLastHeartbeatTime() {
        return lastHeartbeatTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastHeartbeatTime_;
    }

    /**
     * <code>.google.protobuf.Timestamp lastHeartbeatTime = 9;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastHeartbeatTimeOrBuilder() {
        return getLastHeartbeatTime();
    }

    public static final int WORKERSTATUS_FIELD_NUMBER = 10;
    private int workerStatus_;

    /**
     * <code>int32 workerStatus = 10;</code>
     */
    public int getWorkerStatus() {
        return workerStatus_;
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (id_ != 0) {
            output.writeInt32(1, id_);
        }
        if (workerType_ != 0) {
            output.writeInt32(2, workerType_);
        }
        if (!getHostBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, host_);
        }
        if (port_ != 0) {
            output.writeInt32(4, port_);
        }
        if (!getWorkerGroupBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, workerGroup_);
        }
        if (!getZkdirectoryBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 6, zkdirectory_);
        }
        if (cpuUsage_ != 0D) {
            output.writeDouble(7, cpuUsage_);
        }
        if (memoryUsage_ != 0D) {
            output.writeDouble(8, memoryUsage_);
        }
        if (lastHeartbeatTime_ != null) {
            output.writeMessage(9, getLastHeartbeatTime());
        }
        if (workerStatus_ != 0) {
            output.writeInt32(10, workerStatus_);
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;

        size = 0;
        if (id_ != 0) {
            size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, id_);
        }
        if (workerType_ != 0) {
            size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, workerType_);
        }
        if (!getHostBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, host_);
        }
        if (port_ != 0) {
            size += com.google.protobuf.CodedOutputStream.computeInt32Size(4, port_);
        }
        if (!getWorkerGroupBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, workerGroup_);
        }
        if (!getZkdirectoryBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, zkdirectory_);
        }
        if (cpuUsage_ != 0D) {
            size += com.google.protobuf.CodedOutputStream.computeDoubleSize(7, cpuUsage_);
        }
        if (memoryUsage_ != 0D) {
            size += com.google.protobuf.CodedOutputStream.computeDoubleSize(8, memoryUsage_);
        }
        if (lastHeartbeatTime_ != null) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(9, getLastHeartbeatTime());
        }
        if (workerStatus_ != 0) {
            size += com.google.protobuf.CodedOutputStream.computeInt32Size(10, workerStatus_);
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc)) {
            return super.equals(obj);
        }
        com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc other = (com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc) obj;

        boolean result = true;
        result = result && (getId() == other.getId());
        result = result && (getWorkerType() == other.getWorkerType());
        result = result && getHost().equals(other.getHost());
        result = result && (getPort() == other.getPort());
        result = result && getWorkerGroup().equals(other.getWorkerGroup());
        result = result && getZkdirectory().equals(other.getZkdirectory());
        result = result && (java.lang.Double.doubleToLongBits(getCpuUsage()) == java.lang.Double
                .doubleToLongBits(other.getCpuUsage()));
        result = result && (java.lang.Double.doubleToLongBits(getMemoryUsage()) == java.lang.Double
                .doubleToLongBits(other.getMemoryUsage()));
        result = result && (hasLastHeartbeatTime() == other.hasLastHeartbeatTime());
        if (hasLastHeartbeatTime()) {
            result = result && getLastHeartbeatTime().equals(other.getLastHeartbeatTime());
        }
        result = result && (getWorkerStatus() == other.getWorkerStatus());
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + WORKERTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getWorkerType();
        hash = (37 * hash) + HOST_FIELD_NUMBER;
        hash = (53 * hash) + getHost().hashCode();
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
        hash = (37 * hash) + WORKERGROUP_FIELD_NUMBER;
        hash = (53 * hash) + getWorkerGroup().hashCode();
        hash = (37 * hash) + ZKDIRECTORY_FIELD_NUMBER;
        hash = (53 * hash) + getZkdirectory().hashCode();
        hash = (37 * hash) + CPUUSAGE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getCpuUsage()));
        hash = (37 * hash) + MEMORYUSAGE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getMemoryUsage()));
        if (hasLastHeartbeatTime()) {
            hash = (37 * hash) + LASTHEARTBEATTIME_FIELD_NUMBER;
            hash = (53 * hash) + getLastHeartbeatTime().hashCode();
        }
        hash = (37 * hash) + WORKERSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + getWorkerStatus();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc parseFrom(
            com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc parseFrom(
            com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc parseDelimitedFrom(
            java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc parseFrom(
            com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc parseFrom(
            com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code WorkerRequestRpc}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:WorkerRequestRpc)
            com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpcOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.ylpu.thales.scheduler.core.rpc.entity.WorkerGrpc.internal_static_WorkerRequestRpc_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.ylpu.thales.scheduler.core.rpc.entity.WorkerGrpc.internal_static_WorkerRequestRpc_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc.class,
                            com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc.Builder.class);
        }

        // Construct using
        // com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            id_ = 0;

            workerType_ = 0;

            host_ = "";

            port_ = 0;

            workerGroup_ = "";

            zkdirectory_ = "";

            cpuUsage_ = 0D;

            memoryUsage_ = 0D;

            if (lastHeartbeatTimeBuilder_ == null) {
                lastHeartbeatTime_ = null;
            } else {
                lastHeartbeatTime_ = null;
                lastHeartbeatTimeBuilder_ = null;
            }
            workerStatus_ = 0;

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.ylpu.thales.scheduler.core.rpc.entity.WorkerGrpc.internal_static_WorkerRequestRpc_descriptor;
        }

        public com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc getDefaultInstanceForType() {
            return com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc.getDefaultInstance();
        }

        public com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc build() {
            com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc buildPartial() {
            com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc result = new com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc(
                    this);
            result.id_ = id_;
            result.workerType_ = workerType_;
            result.host_ = host_;
            result.port_ = port_;
            result.workerGroup_ = workerGroup_;
            result.zkdirectory_ = zkdirectory_;
            result.cpuUsage_ = cpuUsage_;
            result.memoryUsage_ = memoryUsage_;
            if (lastHeartbeatTimeBuilder_ == null) {
                result.lastHeartbeatTime_ = lastHeartbeatTime_;
            } else {
                result.lastHeartbeatTime_ = lastHeartbeatTimeBuilder_.build();
            }
            result.workerStatus_ = workerStatus_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc) {
                return mergeFrom((com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc other) {
            if (other == com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc.getDefaultInstance())
                return this;
            if (other.getId() != 0) {
                setId(other.getId());
            }
            if (other.getWorkerType() != 0) {
                setWorkerType(other.getWorkerType());
            }
            if (!other.getHost().isEmpty()) {
                host_ = other.host_;
                onChanged();
            }
            if (other.getPort() != 0) {
                setPort(other.getPort());
            }
            if (!other.getWorkerGroup().isEmpty()) {
                workerGroup_ = other.workerGroup_;
                onChanged();
            }
            if (!other.getZkdirectory().isEmpty()) {
                zkdirectory_ = other.zkdirectory_;
                onChanged();
            }
            if (other.getCpuUsage() != 0D) {
                setCpuUsage(other.getCpuUsage());
            }
            if (other.getMemoryUsage() != 0D) {
                setMemoryUsage(other.getMemoryUsage());
            }
            if (other.hasLastHeartbeatTime()) {
                mergeLastHeartbeatTime(other.getLastHeartbeatTime());
            }
            if (other.getWorkerStatus() != 0) {
                setWorkerStatus(other.getWorkerStatus());
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int id_;

        /**
         * <code>int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        /**
         * <code>int32 id = 1;</code>
         */
        public Builder setId(int value) {

            id_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 id = 1;</code>
         */
        public Builder clearId() {

            id_ = 0;
            onChanged();
            return this;
        }

        private int workerType_;

        /**
         * <code>int32 workerType = 2;</code>
         */
        public int getWorkerType() {
            return workerType_;
        }

        /**
         * <code>int32 workerType = 2;</code>
         */
        public Builder setWorkerType(int value) {

            workerType_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 workerType = 2;</code>
         */
        public Builder clearWorkerType() {

            workerType_ = 0;
            onChanged();
            return this;
        }

        private java.lang.Object host_ = "";

        /**
         * <code>string host = 3;</code>
         */
        public java.lang.String getHost() {
            java.lang.Object ref = host_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                host_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string host = 3;</code>
         */
        public com.google.protobuf.ByteString getHostBytes() {
            java.lang.Object ref = host_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                host_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string host = 3;</code>
         */
        public Builder setHost(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            host_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string host = 3;</code>
         */
        public Builder clearHost() {

            host_ = getDefaultInstance().getHost();
            onChanged();
            return this;
        }

        /**
         * <code>string host = 3;</code>
         */
        public Builder setHostBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            host_ = value;
            onChanged();
            return this;
        }

        private int port_;

        /**
         * <code>int32 port = 4;</code>
         */
        public int getPort() {
            return port_;
        }

        /**
         * <code>int32 port = 4;</code>
         */
        public Builder setPort(int value) {

            port_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 port = 4;</code>
         */
        public Builder clearPort() {

            port_ = 0;
            onChanged();
            return this;
        }

        private java.lang.Object workerGroup_ = "";

        /**
         * <code>string workerGroup = 5;</code>
         */
        public java.lang.String getWorkerGroup() {
            java.lang.Object ref = workerGroup_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                workerGroup_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string workerGroup = 5;</code>
         */
        public com.google.protobuf.ByteString getWorkerGroupBytes() {
            java.lang.Object ref = workerGroup_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                workerGroup_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string workerGroup = 5;</code>
         */
        public Builder setWorkerGroup(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            workerGroup_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string workerGroup = 5;</code>
         */
        public Builder clearWorkerGroup() {

            workerGroup_ = getDefaultInstance().getWorkerGroup();
            onChanged();
            return this;
        }

        /**
         * <code>string workerGroup = 5;</code>
         */
        public Builder setWorkerGroupBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            workerGroup_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object zkdirectory_ = "";

        /**
         * <code>string zkdirectory = 6;</code>
         */
        public java.lang.String getZkdirectory() {
            java.lang.Object ref = zkdirectory_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                zkdirectory_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string zkdirectory = 6;</code>
         */
        public com.google.protobuf.ByteString getZkdirectoryBytes() {
            java.lang.Object ref = zkdirectory_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                zkdirectory_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string zkdirectory = 6;</code>
         */
        public Builder setZkdirectory(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            zkdirectory_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string zkdirectory = 6;</code>
         */
        public Builder clearZkdirectory() {

            zkdirectory_ = getDefaultInstance().getZkdirectory();
            onChanged();
            return this;
        }

        /**
         * <code>string zkdirectory = 6;</code>
         */
        public Builder setZkdirectoryBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            zkdirectory_ = value;
            onChanged();
            return this;
        }

        private double cpuUsage_;

        /**
         * <code>double cpuUsage = 7;</code>
         */
        public double getCpuUsage() {
            return cpuUsage_;
        }

        /**
         * <code>double cpuUsage = 7;</code>
         */
        public Builder setCpuUsage(double value) {

            cpuUsage_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>double cpuUsage = 7;</code>
         */
        public Builder clearCpuUsage() {

            cpuUsage_ = 0D;
            onChanged();
            return this;
        }

        private double memoryUsage_;

        /**
         * <code>double memoryUsage = 8;</code>
         */
        public double getMemoryUsage() {
            return memoryUsage_;
        }

        /**
         * <code>double memoryUsage = 8;</code>
         */
        public Builder setMemoryUsage(double value) {

            memoryUsage_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>double memoryUsage = 8;</code>
         */
        public Builder clearMemoryUsage() {

            memoryUsage_ = 0D;
            onChanged();
            return this;
        }

        private com.google.protobuf.Timestamp lastHeartbeatTime_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastHeartbeatTimeBuilder_;

        /**
         * <code>.google.protobuf.Timestamp lastHeartbeatTime = 9;</code>
         */
        public boolean hasLastHeartbeatTime() {
            return lastHeartbeatTimeBuilder_ != null || lastHeartbeatTime_ != null;
        }

        /**
         * <code>.google.protobuf.Timestamp lastHeartbeatTime = 9;</code>
         */
        public com.google.protobuf.Timestamp getLastHeartbeatTime() {
            if (lastHeartbeatTimeBuilder_ == null) {
                return lastHeartbeatTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance()
                        : lastHeartbeatTime_;
            } else {
                return lastHeartbeatTimeBuilder_.getMessage();
            }
        }

        /**
         * <code>.google.protobuf.Timestamp lastHeartbeatTime = 9;</code>
         */
        public Builder setLastHeartbeatTime(com.google.protobuf.Timestamp value) {
            if (lastHeartbeatTimeBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                lastHeartbeatTime_ = value;
                onChanged();
            } else {
                lastHeartbeatTimeBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp lastHeartbeatTime = 9;</code>
         */
        public Builder setLastHeartbeatTime(com.google.protobuf.Timestamp.Builder builderForValue) {
            if (lastHeartbeatTimeBuilder_ == null) {
                lastHeartbeatTime_ = builderForValue.build();
                onChanged();
            } else {
                lastHeartbeatTimeBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp lastHeartbeatTime = 9;</code>
         */
        public Builder mergeLastHeartbeatTime(com.google.protobuf.Timestamp value) {
            if (lastHeartbeatTimeBuilder_ == null) {
                if (lastHeartbeatTime_ != null) {
                    lastHeartbeatTime_ = com.google.protobuf.Timestamp.newBuilder(lastHeartbeatTime_).mergeFrom(value)
                            .buildPartial();
                } else {
                    lastHeartbeatTime_ = value;
                }
                onChanged();
            } else {
                lastHeartbeatTimeBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp lastHeartbeatTime = 9;</code>
         */
        public Builder clearLastHeartbeatTime() {
            if (lastHeartbeatTimeBuilder_ == null) {
                lastHeartbeatTime_ = null;
                onChanged();
            } else {
                lastHeartbeatTime_ = null;
                lastHeartbeatTimeBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp lastHeartbeatTime = 9;</code>
         */
        public com.google.protobuf.Timestamp.Builder getLastHeartbeatTimeBuilder() {

            onChanged();
            return getLastHeartbeatTimeFieldBuilder().getBuilder();
        }

        /**
         * <code>.google.protobuf.Timestamp lastHeartbeatTime = 9;</code>
         */
        public com.google.protobuf.TimestampOrBuilder getLastHeartbeatTimeOrBuilder() {
            if (lastHeartbeatTimeBuilder_ != null) {
                return lastHeartbeatTimeBuilder_.getMessageOrBuilder();
            } else {
                return lastHeartbeatTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance()
                        : lastHeartbeatTime_;
            }
        }

        /**
         * <code>.google.protobuf.Timestamp lastHeartbeatTime = 9;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> getLastHeartbeatTimeFieldBuilder() {
            if (lastHeartbeatTimeBuilder_ == null) {
                lastHeartbeatTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                        getLastHeartbeatTime(), getParentForChildren(), isClean());
                lastHeartbeatTime_ = null;
            }
            return lastHeartbeatTimeBuilder_;
        }

        private int workerStatus_;

        /**
         * <code>int32 workerStatus = 10;</code>
         */
        public int getWorkerStatus() {
            return workerStatus_;
        }

        /**
         * <code>int32 workerStatus = 10;</code>
         */
        public Builder setWorkerStatus(int value) {

            workerStatus_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 workerStatus = 10;</code>
         */
        public Builder clearWorkerStatus() {

            workerStatus_ = 0;
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        // @@protoc_insertion_point(builder_scope:WorkerRequestRpc)
    }

    // @@protoc_insertion_point(class_scope:WorkerRequestRpc)
    private static final com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc();
    }

    public static com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WorkerRequestRpc> PARSER = new com.google.protobuf.AbstractParser<WorkerRequestRpc>() {
        public WorkerRequestRpc parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new WorkerRequestRpc(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<WorkerRequestRpc> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WorkerRequestRpc> getParserForType() {
        return PARSER;
    }

    public com.ylpu.thales.scheduler.core.rpc.entity.WorkerRequestRpc getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}
