// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

package com.ylpu.thales.scheduler.core.rpc.entity;

public final class WorkerGrpc {
  private WorkerGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkerRequestRpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WorkerRequestRpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkerParameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WorkerParameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkerResponseRpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WorkerResponseRpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JobStatusRequestRpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JobStatusRequestRpc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014worker.proto\032\017timestamp.proto\"\346\001\n\020Work" +
      "erRequestRpc\022\n\n\002id\030\001 \001(\005\022\020\n\010nodeType\030\002 \001" +
      "(\005\022\014\n\004host\030\003 \001(\t\022\014\n\004port\030\004 \001(\005\022\021\n\tnodeGr" +
      "oup\030\005 \001(\t\022\023\n\013zkdirectory\030\006 \001(\t\022\020\n\010cpuUsa" +
      "ge\030\007 \001(\001\022\023\n\013memoryUsage\030\010 \001(\001\0225\n\021lastHea" +
      "rtbeatTime\030\t \001(\0132\032.google.protobuf.Times" +
      "tamp\022\022\n\nnodeStatus\030\n \001(\005\"#\n\017WorkerParame" +
      "ter\022\020\n\010hostname\030\001 \001(\t\"R\n\021WorkerResponseR" +
      "pc\022\n\n\002id\030\001 \001(\005\022\021\n\terrorCode\030\002 \001(\005\022\020\n\010err" +
      "orMsg\030\003 \001(\t\022\014\n\004data\030\004 \001(\014\"I\n\023JobStatusRe",
      "questRpc\022\021\n\trequestId\030\001 \001(\t\022\021\n\ttaskState" +
      "\030\002 \001(\005\022\014\n\004data\030\003 \001(\0142\353\001\n\021GrpcWorkerServi" +
      "ce\022/\n\007incTask\022\020.WorkerParameter\032\022.Worker" +
      "ResponseRpc\022/\n\007decTask\022\020.WorkerParameter" +
      "\032\022.WorkerResponseRpc\0227\n\016updateResource\022\021" +
      ".WorkerRequestRpc\032\022.WorkerResponseRpc\022;\n" +
      "\017updateJobStatus\022\024.JobStatusRequestRpc\032\022" +
      ".WorkerResponseRpcB9\n)com.ylpu.thales.sc" +
      "heduler.core.rpc.entityB\nWorkerGrpcP\001P\000b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_WorkerRequestRpc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WorkerRequestRpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WorkerRequestRpc_descriptor,
        new java.lang.String[] { "Id", "NodeType", "Host", "Port", "NodeGroup", "Zkdirectory", "CpuUsage", "MemoryUsage", "LastHeartbeatTime", "NodeStatus", });
    internal_static_WorkerParameter_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WorkerParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WorkerParameter_descriptor,
        new java.lang.String[] { "Hostname", });
    internal_static_WorkerResponseRpc_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_WorkerResponseRpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WorkerResponseRpc_descriptor,
        new java.lang.String[] { "Id", "ErrorCode", "ErrorMsg", "Data", });
    internal_static_JobStatusRequestRpc_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_JobStatusRequestRpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JobStatusRequestRpc_descriptor,
        new java.lang.String[] { "RequestId", "TaskState", "Data", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
